In [2]:
import numpy as np

In [3]:
np.random.seed(42)

In [4]:
matrices = [np.random.randint(-10, 11, size=(3, 3)) for _ in range(3)]

for i, M in enumerate(matrices):
    print(f"{'='*50}")
    print(f"MATRIX {i+1}")
    print(f"{'='*50}")
    print(f"\nM{i+1} =")
    print(M)
    
    # Compute determinant to check if inverse exists
    det = np.linalg.det(M)
    print(f"\nDeterminant: {det:.4f}")
    
    if np.abs(det) > 1e-10:  # Matrix is invertible
        # Compute inverse
        M_inv = np.linalg.inv(M)
        print(f"\nM{i+1}^(-1) =")
        print(np.round(M_inv, 4))
        
        # Verification: M @ M_inv should equal identity matrix
        product = M @ M_inv
        print(f"\nVerification: M{i+1} @ M{i+1}^(-1) =")
        print(np.round(product, 10))
        
        # Confirm result is identity
        identity = np.eye(3)
        is_identity = np.allclose(product, identity)
        print(f"\nEquals identity matrix? {is_identity} ✓" if is_identity else f"\nEquals identity matrix? {is_identity} ✗")
    else:
        print("\nMatrix is SINGULAR - no inverse exists")
    
    print()

MATRIX 1

M1 =
[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]

Determinant: -88.0000

M1^(-1) =
[[ 0.9091 -0.3636 -1.1591]
 [ 0.4545 -0.1818 -0.4545]
 [ 0.1364  0.0455 -0.1364]]

Verification: M1 @ M1^(-1) =
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]

Equals identity matrix? True ✓

MATRIX 2

M2 =
[[ 0 10 -7]
 [-3 -8 10]
 [-9  1 -5]]

Determinant: -525.0000

M2^(-1) =
[[-0.0571 -0.0819 -0.0838]
 [ 0.2     0.12   -0.04  ]
 [ 0.1429  0.1714 -0.0571]]

Verification: M2 @ M2^(-1) =
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

Equals identity matrix? True ✓

MATRIX 3

M3 =
[[ -9  10 -10]
 [  1   1   6]
 [ -1   5   4]]

Determinant: 74.0000

M3^(-1) =
[[-0.3514 -1.2162  0.9459]
 [-0.1351 -0.6216  0.5946]
 [ 0.0811  0.473  -0.2568]]

Verification: M3 @ M3^(-1) =
[[ 1. -0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

Equals identity matrix? True ✓

